PKGNAME=wlroots0.20-vmwgfx
PACKAGE_TEMPLATE=source-meson
UPSTREAM_TYPE=custom-hook

PKGDESC="Modular Wayland compositor library with a vmwgfx compatibility patch"
URL="https://gitlab.freedesktop.org/wlroots/wlroots"
LICENSES=('MIT')
ARCHES=('x86_64')
DEPENDS=('glibc' 'libdisplay-info.so' 'libdrm' 'libglvnd' 'libinput' 'liblcms2.so' 'libliftoff.so' 'libpixman-1.so'
         'libseat.so' 'libudev.so' 'libvulkan.so' 'libwayland-client.so' 'libwayland-server.so' 'libxcb' 'libxkbcommon.so'
         'wayland-protocols' 'opengl-driver' 'xcb-util-errors' 'xcb-util-renderutil' 'xcb-util-wm')
MAKEDEPENDS=('git' 'glslang' 'meson' 'ninja' 'systemd' 'vulkan-headers' 'xorg-xwayland')
CHECKDEPENDS=()
OPTDEPENDS=('xorg-xwayland: Xwayland support'
            'vulkan-validation-layers: validation layers for the experimental vulkan renderer backend')
OPTIONS=()
PROVIDES=('libwlroots-0.20.so' 'wlroots0.20')
CONFLICTS=('wlroots0.20')
VALIDPGPKEYS=('34FF9526CFEF0E97A340E2E40FDE7BE0E88F5E48'  # Simon Ser
              '9DDA3B9FA5D58DD5392C78E652CB6609B22DA89A'  # Drew DeVault
              '4100929B33EEB0FD1DB852797BC79407090047CA') # Sway signing key

SOURCE_RENAME='${pkgname}'
SOURCE_DIR='${pkgname}'
BUILD_DIR=build
PATCH_FILES=('files/0001-vmwgfx-disable-dmabuf-import-check-after-close-failure.patch')
MESON_OPTIONS=()
RUN_CHECK=false
CHECK_ARGS=()

LOCAL_FILES=()
DOC_FILES=()
LICENSE_FILES=('LICENSE')

INSTALL_MODE=none
SERVICE_MODE=none
