PKGNAME=zellij-no-mouse-resize-bin
PACKAGE_TEMPLATE=binary-archive
UPSTREAM_TYPE=custom-hook

PKGDESC="Zellij with advanced_mouse_actions also gating pane mouse resize (binary)"
URL="https://zellij.dev"
LICENSES=('MIT')
ARCHES=('x86_64')
DEPENDS=('curl' 'libcurl.so' 'glibc' 'libgcc' 'libgcc_s.so' 'zlib' 'libz.so')
MAKEDEPENDS=()
CHECKDEPENDS=()
OPTDEPENDS=()
OPTIONS=('!strip')
PROVIDES=('zellij' 'zellij-no-mouse-resize')
CONFLICTS=('zellij' 'zellij-bin' 'zellij-git' 'zellij-no-mouse-resize')
VALIDPGPKEYS=()

SOURCE_RENAME_X86_64='${pkgname}-${pkgver}-x86_64.tar.gz'

BINARY_NAME=zellij
BINARY_SOURCE_PATH=zellij
INSTALL_BIN_PATH=/usr/bin/zellij

LOCAL_FILES=()
DOC_FILES=('README.md')
LICENSE_FILES=('LICENSE.md')

INSTALL_MODE=none
SERVICE_MODE=none

TEST_PATHS=()
TEST_EXECUTABLES=()
TEST_COMMANDS=('/usr/bin/zellij --version')
